image: node:latest

default:
    tags:
        - "node:latest"

stages:
    - build
    - test

cache:
    paths:
        - node_modules/

install:
    stage: build
    script:
        - npm install
        - wget -q http://georgms.github.io/textsearch102/files/simple-wikipedia.zip && unzip -q simple-wikipedia.zip
        - ls -R
    artifacts:
        paths:
            - node_modules/

test:
    stage: test
    script:
        - npm run lint
        - npm run test
